ARG NODE_VERSION=20.11.0

FROM node:${NODE_VERSION}-alpine as builder

RUN corepack enable pnpm
RUN corepack prepare pnpm@8.15.4 --activate
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN pnpm i
COPY . .
RUN pnpm run build
RUN ls -la /app/.next


FROM node:${NODE_VERSION}-alpine as runner
RUN apk add --no-cache libc6-compat curl
RUN corepack enable pnpm
RUN corepack prepare pnpm@8.15.4 --activate

WORKDIR /app

COPY --from=builder /app/.next/ /app/.next/
RUN ls -la /app/.next/

COPY package.json package.json
RUN pnpm install --prod

CMD pnpm dev